import { END_MARKER, START_MARKER } from "./delivery.js";
import {
  DEFAULT_RANKING_TRIALS_THRESHOLD,
  rankingRateForRow,
  type RankingBlob,
} from "./ranking.js";
import type { MigrationRule } from "./rule-match.js";
import type { MatchRow } from "./types.js";

export const MAX_MARKDOWN_BYTES = 8 * 1024;
/** Managed-block budget in the delivery file (1.5 KiB). */
export const MAX_EMBED_BYTES = 1536;

export type TruncationRankingOpts = {
  ranking?: RankingBlob | null;
  trialsThreshold?: number;
};

export type MarkdownRuleKnowledge = {
  /** Rules to embed under matching package rows (message + optional fix). */
  rules?: MigrationRule[];
};

const DOC_TITLE = `# Dependency version notes

Generated by aieph.

`;

function recentIntro(windowMonths: number): string {
  return (
    `### Recently released majors\n` +
    `\n` +
    `These majors were released within the last ${windowMonths} months. Your knowledge\n` +
    `of their API may predate them. Check the notes before writing code\n` +
    `against them.\n` +
    `\n` +
    `| package | in use | released | notes |\n` +
    `|---|---|---|---|\n`
  );
}

const MINORITY_INTRO =
  `### Non-default majors\n` +
  `\n` +
  `Most of the ecosystem uses a different major. Your defaults will drift\n` +
  `toward the mainstream version. This project stays on the version below.\n` +
  `\n` +
  `| package | in use | ecosystem majority | share of in-use | notes |\n` +
  `|---|---|---|---|---|\n`;

function pct(share: number | null): string {
  if (share === null || !Number.isFinite(share)) return "—";
  return `${Math.round(share * 100)}%`;
}

/**
 * Local truncation priority: lower pinnedShare first (kept).
 * Null pinnedShare: prefer newer released (desc) as secondary.
 */
function compareLocalOrder(a: MatchRow, b: MatchRow): number {
  const aShare = a.pinnedShare;
  const bShare = b.pinnedShare;
  if (aShare === null && bShare === null) {
    if (a.released !== b.released) {
      return a.released < b.released ? 1 : -1;
    }
    return a.name.localeCompare(b.name);
  }
  if (aShare === null) return -1;
  if (bShare === null) return 1;
  if (aShare !== bShare) return aShare - bShare;
  if (a.released !== b.released) {
    return a.released < b.released ? 1 : -1;
  }
  return a.name.localeCompare(b.name);
}

/**
 * Truncation priority:
 * - Ranked (trials >= threshold): hit rate descending, always before unranked.
 * - Unranked / below threshold: lower pinnedShare first (local order).
 */
export function sortForTruncation(
  rows: MatchRow[],
  opts?: TruncationRankingOpts,
): MatchRow[] {
  const ranking = opts?.ranking ?? null;
  const threshold = opts?.trialsThreshold ?? DEFAULT_RANKING_TRIALS_THRESHOLD;
  if (!ranking) {
    return [...rows].sort(compareLocalOrder);
  }
  return [...rows].sort((a, b) => {
    const aRate = rankingRateForRow(a, ranking, threshold);
    const bRate = rankingRateForRow(b, ranking, threshold);
    const aRanked = aRate !== null;
    const bRanked = bRate !== null;
    if (aRanked && bRanked) {
      if (aRate !== bRate) return (bRate as number) - (aRate as number);
      return a.name.localeCompare(b.name);
    }
    if (aRanked && !bRanked) return -1;
    if (!aRanked && bRanked) return 1;
    return compareLocalOrder(a, b);
  });
}

function recentRowLine(r: MatchRow): string {
  return `| ${r.name} | ${r.inUseMajor} | ${r.released} | ${r.notes} |\n`;
}

function minorityRowLine(r: MatchRow): string {
  const maj =
    r.majorityMajor === null || r.majorityMajor === undefined
      ? "—"
      : String(r.majorityMajor);
  return `| ${r.name} | ${r.inUseMajor} | ${maj} | ${pct(r.pinnedShare)} | ${r.notes} |\n`;
}

function splitClasses(rows: MatchRow[]): {
  recent: MatchRow[];
  minority: MatchRow[];
} {
  return {
    recent: rows.filter((r) => r.which === "recent"),
    minority: rows.filter((r) => r.which === "minority"),
  };
}

function rowKey(r: MatchRow): string {
  return `${r.which}\0${r.name}\0${r.inUseMajor}`;
}

function rulesForPackage(
  rules: MigrationRule[] | undefined,
  pkg: string,
  fromMajor: number,
): MigrationRule[] {
  if (!rules || rules.length === 0) return [];
  return rules.filter(
    (r) => r.package === pkg && r.from_major === fromMajor,
  );
}

function renderRuleSection(pkg: string, rules: MigrationRule[]): string {
  if (rules.length === 0) return "";
  let s = `\n#### ${pkg} — rewrite knowledge\n\n`;
  for (const r of rules) {
    s += `- **${r.id}**: ${r.message}`;
    if (r.fix?.trim()) s += ` ${r.fix.trim()}`;
    s += `\n`;
  }
  return s;
}

function renderBody(
  recent: MatchRow[],
  minority: MatchRow[],
  windowMonths: number,
): string {
  let s = "";
  if (recent.length > 0) {
    s += recentIntro(windowMonths);
    for (const r of recent) s += recentRowLine(r);
    if (minority.length > 0) s += "\n";
  }
  if (minority.length > 0) {
    s += MINORITY_INTRO;
    for (const r of minority) s += minorityRowLine(r);
  }
  return s;
}

function renderKnowledge(
  rows: MatchRow[],
  rules: MigrationRule[] | undefined,
  packageAllow: Set<string> | null,
): string {
  if (!rules || rules.length === 0) return "";
  let s = "";
  const seen = new Set<string>();
  for (const row of rows) {
    const key = `${row.name}\0${row.inUseMajor}`;
    if (seen.has(key)) continue;
    seen.add(key);
    if (packageAllow && !packageAllow.has(row.name)) continue;
    const pkgRules = rulesForPackage(rules, row.name, row.inUseMajor);
    s += renderRuleSection(row.name, pkgRules);
  }
  return s;
}

function renderKnowledgeFromRules(
  selected: MigrationRule[],
): string {
  if (selected.length === 0) return "";
  const byPkg = new Map<string, MigrationRule[]>();
  for (const r of selected) {
    const list = byPkg.get(r.package) ?? [];
    list.push(r);
    byPkg.set(r.package, list);
  }
  let s = "";
  const seen = new Set<string>();
  for (const r of selected) {
    if (seen.has(r.package)) continue;
    seen.add(r.package);
    s += renderRuleSection(r.package, byPkg.get(r.package)!);
  }
  return s;
}

/**
 * Order matching rules for embed truncation:
 * packages by sortForTruncation; within a package, ranked rules
 * (trials >= threshold) by hit rate desc, then unranked in file order.
 */
function sortRulesForEmbed(
  matching: MigrationRule[],
  rows: MatchRow[],
  rankingOpts?: TruncationRankingOpts,
): MigrationRule[] {
  const rowByPkg = new Map<string, MatchRow>();
  for (const row of rows) {
    const key = `${row.name}\0${row.inUseMajor}`;
    if (!rowByPkg.has(key)) rowByPkg.set(key, row);
  }
  const pkgRows = sortForTruncation(
    [...rowByPkg.values()].filter((row) =>
      matching.some(
        (r) => r.package === row.name && r.from_major === row.inUseMajor,
      ),
    ),
    rankingOpts,
  );
  const ranking = rankingOpts?.ranking ?? null;
  const threshold =
    rankingOpts?.trialsThreshold ?? DEFAULT_RANKING_TRIALS_THRESHOLD;
  const out: MigrationRule[] = [];
  for (const row of pkgRows) {
    const pkgRules = matching.filter(
      (r) => r.package === row.name && r.from_major === row.inUseMajor,
    );
    if (!ranking) {
      out.push(...pkgRules);
      continue;
    }
    const ranked: { rule: MigrationRule; rate: number }[] = [];
    const unranked: MigrationRule[] = [];
    for (const rule of pkgRules) {
      const stats = ranking.rules[rule.id];
      if (stats && stats.trials >= threshold && stats.trials > 0) {
        ranked.push({ rule, rate: stats.hits / stats.trials });
      } else {
        unranked.push(rule);
      }
    }
    ranked.sort((a, b) => b.rate - a.rate || a.rule.id.localeCompare(b.rule.id));
    out.push(...ranked.map((x) => x.rule), ...unranked);
  }
  return out;
}

/**
 * Build versions.md. Sections only for non-empty classes.
 * When rules are provided, append per-package rewrite knowledge.
 * Over 8 KiB with rules: drop rule sections by pinnedShare ascending
 * (highest share dropped first); tables stay intact.
 * Without rules: truncate table rows as before.
 */
export function buildMarkdown(
  rows: MatchRow[],
  windowMonths: number,
  rankingOpts?: TruncationRankingOpts,
  knowledge?: MarkdownRuleKnowledge,
): string {
  const { recent, minority } = splitClasses(rows);
  if (recent.length === 0 && minority.length === 0) return "";

  const rules = knowledge?.rules;
  const hasRules = Boolean(rules && rules.length > 0);
  const packagesWithRules = new Set(
    (rules ?? [])
      .filter((r) =>
        rows.some((row) => row.name === r.package && row.inUseMajor === r.from_major),
      )
      .map((r) => r.package),
  );

  if (hasRules && packagesWithRules.size > 0) {
    const tableRows = sortForTruncation([...recent, ...minority], rankingOpts);
    const keepRecent = sortForTruncation(recent, rankingOpts);
    const keepMinority = sortForTruncation(minority, rankingOpts);
    const tableBody = renderBody(keepRecent, keepMinority, windowMonths);

    // pinnedShare ascending = keep first; drop from end
    const rulePriority = [...tableRows]
      .filter((r) => packagesWithRules.has(r.name))
      .sort(compareLocalOrder);
    const allowed = new Set(rulePriority.map((r) => r.name));

    const assemble = (): string => {
      let doc =
        DOC_TITLE +
        tableBody +
        renderKnowledge(tableRows, rules, allowed);
      if (!doc.endsWith("\n")) doc += "\n";
      return doc;
    };

    let doc = assemble();
    if (Buffer.byteLength(doc, "utf8") <= MAX_MARKDOWN_BYTES) return doc;

    for (let i = rulePriority.length - 1; i >= 0; i--) {
      allowed.delete(rulePriority[i]!.name);
      doc = assemble();
      if (Buffer.byteLength(doc, "utf8") <= MAX_MARKDOWN_BYTES) return doc;
    }
    return doc;
  }

  const priority = sortForTruncation([...recent, ...minority], rankingOpts);
  const kept = new Set(priority.map(rowKey));

  const assemble = (omitted: number): string => {
    const keepRecent = sortForTruncation(
      recent.filter((r) => kept.has(rowKey(r))),
      rankingOpts,
    );
    const keepMinority = sortForTruncation(
      minority.filter((r) => kept.has(rowKey(r))),
      rankingOpts,
    );
    let doc = DOC_TITLE + renderBody(keepRecent, keepMinority, windowMonths);
    if (omitted > 0) doc += `\n(truncated: ${omitted} more)\n`;
    else if (!doc.endsWith("\n")) doc += "\n";
    return doc;
  };

  let omitted = 0;
  let doc = assemble(0);
  if (Buffer.byteLength(doc, "utf8") <= MAX_MARKDOWN_BYTES) return doc;

  for (let i = priority.length - 1; i >= 0; i--) {
    if (kept.size <= 1) break;
    kept.delete(rowKey(priority[i]!));
    omitted = priority.length - kept.size;
    doc = assemble(omitted);
    if (Buffer.byteLength(doc, "utf8") <= MAX_MARKDOWN_BYTES) return doc;
  }
  return doc;
}

/**
 * M0-T: force aieph_search before answering (≤400 chars; target ~250).
 * Presentation: after rule knowledge, before version tables. Budget: reserved first.
 */
export const M0_T_INSTRUCTION =
  "Before answering about error meanings, library usage, or version-dependent behavior, call `aieph_search` once. On `found:false` (immediate), proceed normally. Never send code, file contents, or chat history—general questions only.\n\n";

/**
 * Build the managed AGENTS.md block (≤ 1.5 KiB).
 * Budget order: M0-T instruction → matching rule knowledge → version tables.
 * Truncate by ranking (when provided) then pinnedShare ascending;
 * always keep a pointer to .aieph/versions.md when content is truncated.
 */
export function buildEmbedBlock(
  rows: MatchRow[],
  windowMonths: number,
  includeFullList: boolean,
  rankingOpts?: TruncationRankingOpts,
  knowledge?: MarkdownRuleKnowledge,
): string {
  if (rows.length === 0) return "";

  const { recent, minority } = splitClasses(rows);
  const priority = sortForTruncation([...recent, ...minority], rankingOpts);
  const rules = knowledge?.rules;

  const fullListLine = includeFullList
    ? `\nFull list: .aieph/versions.md\n`
    : `\n`;
  const closing = `${fullListLine}${END_MARKER}`;
  const header = `${START_MARKER}\n## Dependency versions\n\n`;

  const matchingRules = (rules ?? []).filter((r) =>
    rows.some(
      (row) => row.name === r.package && row.inUseMajor === r.from_major,
    ),
  );
  const ruleOrder = sortRulesForEmbed(matchingRules, priority, rankingOpts);

  const assemble = (
    keptRules: MigrationRule[],
    includeM0T: boolean,
    keptRecent: MatchRow[],
    keptMinority: MatchRow[],
    omittedRows: number,
  ): string => {
    const knowledgePart = renderKnowledgeFromRules(keptRules);
    const m0tPart = includeM0T ? M0_T_INSTRUCTION : "";
    const body = renderBody(keptRecent, keptMinority, windowMonths);
    const truncNotice =
      omittedRows > 0
        ? `\n(${omittedRows} more in .aieph/versions.md)\n`
        : "";
    // Presentation order: knowledge → M0-T → tables; budget reserves M0-T first.
    return header + knowledgePart + m0tPart + body + truncNotice + closing;
  };

  const fits = (s: string): boolean =>
    Buffer.byteLength(s, "utf8") <= MAX_EMBED_BYTES;

  // 1) Reserve M0-T first (highest budget priority).
  let includeM0T = fits(assemble([], true, [], [], 0));

  // 2) Pack rule knowledge into remaining budget (per-rule truncation order).
  const keptRules: MigrationRule[] = [];
  for (const rule of ruleOrder) {
    const trial = [...keptRules, rule];
    const candidate = assemble(trial, includeM0T, [], [], 0);
    if (!fits(candidate)) {
      if (keptRules.length === 0) continue;
      break;
    }
    keptRules.push(rule);
  }

  // 3) Pack version table rows with remaining budget.
  const keptRecent: MatchRow[] = [];
  const keptMinority: MatchRow[] = [];
  let includedRows = 0;

  for (let i = 0; i < priority.length; i++) {
    const r = priority[i]!;
    const trialRecent =
      r.which === "recent" ? [...keptRecent, r] : keptRecent;
    const trialMinority =
      r.which === "minority" ? [...keptMinority, r] : keptMinority;
    const leftAfter = priority.length - i - 1;
    const candidate = assemble(
      keptRules,
      includeM0T,
      trialRecent,
      trialMinority,
      leftAfter,
    );
    if (!fits(candidate)) {
      if (keptRules.length > 0 || includeM0T || includedRows > 0) break;
      continue;
    }
    if (r.which === "recent") keptRecent.push(r);
    else keptMinority.push(r);
    includedRows++;
  }

  let omittedRows = priority.length - includedRows;
  let result = assemble(
    keptRules,
    includeM0T,
    keptRecent,
    keptMinority,
    omittedRows,
  );
  // Trunc notice may push over after packing — shed tables, then rules, then M0-T.
  while (!fits(result)) {
    if (includedRows > 0) {
      if (keptMinority.length > 0) keptMinority.pop();
      else keptRecent.pop();
      includedRows--;
      omittedRows = priority.length - includedRows;
    } else if (keptRules.length > 0) {
      keptRules.pop();
      omittedRows = priority.length;
    } else if (includeM0T) {
      includeM0T = false;
      omittedRows = priority.length;
    } else {
      result = assemble([], false, [], [], 0);
      break;
    }
    result = assemble(
      keptRules,
      includeM0T,
      keptRecent,
      keptMinority,
      omittedRows,
    );
  }
  return result;
}

export function formatSkipBreakdown(
  skipped: Record<string, number>,
): string {
  const parts: string[] = [];
  for (const key of [
    "workspace",
    "file",
    "link",
    "git",
    "ambiguous",
    "types",
  ]) {
    const n = skipped[key] ?? 0;
    if (n > 0) parts.push(`${key}: ${n}`);
  }
  return parts.length > 0 ? parts.join(", ") : "none";
}
